steps:
  - name: maven:3.8.3-openjdk-17
    entrypoint: mvn
    args: ["package","-DskipTests"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/helloworldweb","."]
images: ['gcr.io/$PROJECT_ID/helloworldweb']
