pipeline:
  identifier: Build_godfreym1978_HelloWorldWeb_1727272180659
  name: Build HelloWorldWeb
  orgIdentifier: default
  projectIdentifier: helloworld
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: godfreym1978/HelloWorldWeb
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushGCR
                  name: BuildAndPushGCR_1
                  identifier: BuildAndPushGCR_1
                  spec:
                    connectorRef: gpmgcp3q24
                    host: gcr.io
                    projectID: steam-insight-430414-n9
                    imageName: helloworld
                    tags:
                      - test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - stage:
        name: godfrey-approval
        identifier: godfreyapproval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: godfrey approval
                  identifier: godfrey_approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: k8-deployment-prod
        identifier: k8deploymentprod
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: gke
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: k8dev
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
