pipeline:
  identifier: Build_godfreym1978_HelloWorldWeb_1727272180659
  name: Build HelloWorldWeb
  orgIdentifier: default
  projectIdentifier: helloworld
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: godfreym1978/HelloWorldWeb
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushGCR
                  name: BuildAndPushGCR_1
                  identifier: BuildAndPushGCR_1
                  spec:
                    connectorRef: gpmgcp3q24
                    host: gcr.io
                    projectID: steam-insight-430414-n9
                    imageName: helloworld
                    tags:
                      - test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
